#!/bin/sh
#======================================================================
#                    L W P L O T _ T L 
#                    doc: Thu Oct 13 10:51:49 2011
#                    dlm: Mon Nov 14 15:27:35 2011
#                    (c) 2011 A.M. Thurnherr
#                    uE-Info: 31 88 NIL 0 0 72 2 2 4 NIL ofnI
#======================================================================

# HISTORY:
#	Oct 13, 2011: - created
#	Oct 14, 2011: - fiddled
#	Oct 17, 2011: - turned into filter
#				  - added %run_label
#	Nov 14, 2011: - added file layout check

USAGE="Usage: $0 <eps-file> [in-file]"
	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
eps_file="$1"

while [ -z "$fields" ]
do
	read line
    [ ! -t 1 ] && echo "$line"
	[ -z "$out_basename" ] && out_basename=`expr -- "$line" : '#ANTS#PARAMS#.*out_basename{\([^}]*\)}`
	[ -z "$run_label" ] && run_label=`expr -- "$line" : '#ANTS#PARAMS#.*run_label{\([^}]*\)}`
	[ -z "$min_elapsed" ] && min_elapsed=`expr -- "$line" : '#ANTS#PARAMS#.*elapsed.min{\([^}]*\)}`
	[ -z "$max_elapsed" ] && max_elapsed=`expr -- "$line" : '#ANTS#PARAMS#.*elapsed.max{\([^}]*\)}`
	[ -z "$best_scan_offset" ] && best_scan_offset=`expr -- "$line" : '#ANTS#PARAMS#.*best_scan_offset{\([^}]*\)}`
	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
done

set -- $fields
[ "$1" = elapsed -a "$2" = scan_offset -a "$4" = downcast ] || {
	echo "$0: file layout error ($1,$2,$4)" >&2
	exit 1
}

TMPFILE=/tmp/$$.LWplot_TL
if [ ! -t 1 ]
then
	tee $TMPFILE
else
	cat > $TMPFILE
fi

[ -f .gmtdefaults4 ] ||
	gmtset	PAPER_MEDIA letter+ \
			LABEL_FONT_SIZE 14 ANNOT_FONT_SIZE_PRIMARY 14 \
			WANT_EURO_FONT true \
	        PLOT_DEGREE_FORMAT ddd:mm:ssF

R=-R`echo $min_elapsed/60|bc`/`echo $max_elapsed/60+1|bc`/-24/24
U=-R0/1/0/1
J=-JX10

awk '{if ($4 == 1) { print $1/60,$2; }}' $TMPFILE \
	| psxy -P -K $J $R \
		   -Bf1a15:"Elapsed Time [min]":/f1a5:"Best Offset [scans]":WeSn \
		   -Sc0.1 -Gcoral \
	> "$eps_file"		   
	
awk '{if ($4 == 0) { print $1/60,$2; }}' $TMPFILE \
	| psxy -O -K $J $R -Sc0.1 -GSeaGreen \
	>> "$eps_file"		   
	
echo 0.02 0.98 12 0 0 TL $out_basename $run_label | pstext -O -K $U $J >> "$eps_file"

echo -e "`echo $min_elapsed/60|bc` $best_scan_offset\n`echo $max_elapsed/60+1|bc` $best_scan_offset" \
	| psxy -O $R $J >> "$eps_file"

rm $TMPFILE
fixbb "$eps_file"
