#!/bin/ksh
#======================================================================
#                    L W P L O T _ T L H I S T 
#                    doc: Thu Oct 13 10:51:49 2011
#                    dlm: Mon Mar 12 21:12:43 2012
#                    (c) 2011 A.M. Thurnherr
#                    uE-Info: 16 0 NIL 0 0 72 2 2 4 NIL ofnI
#======================================================================

# HISTORY:
#	Oct 13, 2011: - created
#	Oct 17, 2011: - turned into filter
#				  - added %run_label
#   Nov 14, 2011: - added file layout check
#	Mar 12, 2012: - sh -> ksh as this does not work with /bin/sh on MacOSX 10.6.4

USAGE="Usage: $0 <eps-file> [in-file]"
	[ $# -eq 2 ] && exec <"$2" "$0" "$1"
	[ $# -ne 1 ] && { echo $USAGE >&2; exit 1; }
eps_file="$1"

while [ -z "$fields" ]
do
	read line
    [ ! -t 1 ] && echo "$line"
	[ -z "$out_basename" ] && out_basename=`expr -- "$line" : '#ANTS#PARAMS#.*out_basename{\([^}]*\)}`
	[ -z "$run_label" ] && run_label=`expr -- "$line" : '#ANTS#PARAMS#.*run_label{\([^}]*\)}`
	[ -z "$n_windows" ] && n_windows=`expr -- "$line" : '#ANTS#PARAMS#.*n_windows{\([^}]*\)}`
	[ -z "$best_scan_offset" ] && best_scan_offset=`expr -- "$line" : '#ANTS#PARAMS#.*best_scan_offset{\([^}]*\)}`
	[ -z "$fields" ] && fields=`expr -- "$line" : '#ANTS#FIELDS# \(.*\)' | sed -e s/{//g -e s/}//g`
done

set -- $fields
[ "$1" = scan_offset -a "$2" = nsamp ] || {
	echo "$0: file layout error" >&2
	exit 1
}

TMPFILE=/tmp/$$.LWplot_TLhist
if [ ! -t 1 ]
then
	tee $TMPFILE
else
	cat > $TMPFILE
fi

[ -f .gmtdefaults4 ] ||
	gmtset	PAPER_MEDIA letter+ \
			LABEL_FONT_SIZE 14 ANNOT_FONT_SIZE_PRIMARY 14 \
			WANT_EURO_FONT true \
	        PLOT_DEGREE_FORMAT ddd:mm:ssF

R=-R-24/24/0/60
U=-R0/1/0/1
J=-JX10

awk "{print \$1, 100*\$2/$n_windows}" $TMPFILE \
	| psxy -P -K $J $R \
			-Bf1a10:"Best Offset [scans]":/f1a5:"Fraction [%]":WeSn \
		    -Sb1u -G127 > "$eps_file"
	
echo 0.02 0.98 12 0 0 TL $out_basename $run_label | pstext -O -K $J $U >> "$eps_file"

echo -e "$best_scan_offset 0\n$best_scan_offset 60" \
	| psxy -O $J $R >> "$eps_file"

rm $TMPFILE
fixbb "$eps_file"
